id = "nushu-theme"
name = "Nushu"
version = "0.1.1"
schema_version = 1
authors = ["Hunter Jennings <jenningsdhunter@gmail.com>"]
description = "A port of the amazing Nushu VSCode theme for Zed Editor"
repository = "https://github.com/h-jennings/nushu-zed-theme"

[contributes]
themes = ["themes/nushu-theme.json"]
