id = "nushu-theme"
name = "Nushu"
version = "0.1.0"
schema_version = 1
authors = ["Hunter Jennings <jenningsdhunter@gmail.com>"]
description = "A port of the amazing Nushu VSCode theme for Zed Editor"

[contributes]
themes = ["themes/nushu-theme.json"]
